baseURL = "https://example.com"
languageCode = "en-US"
DefaultContentLanguage = "zh"
title = "tianhe说"
paginate = 5
enableEmoji = true
summaryLength = 200
hasCJKLanguage = true

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[params]
# Used to check if the theme is configured correctly
version = "v1.1.0"
# If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
debug = false
# Podcast image URL
podcastImage = "https://tianheg.co/images/logo.png"
# If you leave it blank, will generate RSS Feed automatically by episodes you posted, or you can specify your podcast RSS feed URL
podcastRSS = ""
# Site creation time
since = "2024"
# Description will displayed in the sidebar
description = "tianhe说是一个关于读书的播客。"
keywords = ["Hugo", "theme", "podcast"]
# Post types that will displayed on the home page
mainSections = ["episode"]
# The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
dateFormatToUse = "2006-01-02"
# Syntax highlighting by highlight.js
# When set highlightInClient to false, please uncomment the [markup.highlight] section below
highlightInClient = true
# Enable KaTeX
katex = false
# Paginate of archives, tags and categories
archivePaginate = 20

# Podcast category
[[params.podcastCategory]]
title = "Society & Culture"
subTitle = "Personal Journals"

[[params.podcastCategory]]
title = "Society & Culture"
subTitle = "Relationships"

[[params.podcastCategory]]
title = "Society & Culture"
subTitle = "Documentary"

# Podcast related links displayed in the sidebar
# If leave link field blank, the link will not displayed in the sidebar
# Specify icon by fontAwesome or svg field:
# If using fontAwesome simply fill the fontAwesome field with class name of icon
# If using svg, you need put your svg icon to /static/icons/, then specify the svg field
[[params.links]]
title = "Apple Podcast"
fontAwesomeIcon = "fas fa-podcast"
link = ""
svg = ""

[[params.links]]
title = "Google Podcast"
fontAwesomeIcon = "fab fa-google"
link = ""
svg = ""

[[params.links]]
title = "Pocket Casts"
fontAwesomeIcon = ""
link = ""
svg = "/icons/pocketcasts.svg"

[[params.links]]
title = "Overcast"
fontAwesomeIcon = ""
link = ""
svg = "/icons/overcast.svg"

[[params.links]]
title = "Castro"
fontAwesomeIcon = ""
link = ""
svg = "/icons/castro.svg"

[[params.links]]
title = "小宇宙"
fontAwesomeIcon = ""
link = "https://www.xiaoyuzhoufm.com/podcast/657a9e749c83789819bdf390"
svg = "/icons/cosmos.svg"

[[params.links]]
title = "喜马拉雅"
fontAwesomeIcon = ""
link = ""
svg = "/icons/ximalaya.svg"

[[params.links]]
title = "网易云"
fontAwesomeIcon = ""
link = ""
svg = "/icons/netease.svg"

[[params.links]]
title = "汽水儿"
fontAwesomeIcon = "fas fa-headphones-alt"
link = ""
svg = ""

[[params.links]]
title = "皮艇"
fontAwesomeIcon = "fas fa-headphones-alt"
link = ""
svg = ""

[[params.links]]
title = "微博"
fontAwesomeIcon = "fab fa-weibo"
link = ""
svg = ""

[[params.links]]
title = "Email"
fontAwesomeIcon = "fas fa-envelope"
link = "mailto:podcast@tianheg.co"
svg = ""

[markup]
[markup.goldmark.renderer]
unsafe = true
